name: Angular App Parsing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install
          npm install @angular/compiler
      - name: Parse Angular App and Generate Docs
        run: |
          # Add your script to parse and generate docs here
